### ISSUE TITLE
Automatically set the right field value when the beneficiary's bank is STP.

### ISSUE THREAD

**Issue by pachCode** [cuenca-mx/stpmex-python#13]

**Comment by matin** [comment]
It's not so much about "allowing" an intra-STP Orden. The field value for third-party is a default and could be set by the library consumer. It's more about automatically setting the right field value when the beneficiary's bank is STP.

**Comment by pachCode** [comment]
STP allow transaction from stp to stp, they only not allow transaction from the same account in stp. For that case the validation will be in the core
