### ISSUE TITLE
 SignatureValidationError when prioridad is 0

### ISSUE THREAD

**Issue by froysm** [cuenca-mx/stpmex-python#145]
## Expected Behavior

An order with `prioridad` as `0` should still generate a valid signature.

## Current Behavior

The following error is raised when the parameter `prioridad` is `0`:

```
stpmex.exc.SignatureValidationError: SignatureValidationError(descripcionError='Error validando la firma', id=0)
```

## Possible Solution

The issue lies in the generated string for the signature and the signature itself since the character considered for the field `prioridad`, when it is `0`, is included in the generated signature, for example:

```
||40072|TAMIZI|||CR1607909706|90646|1.20|1|40||646180110400000007||40|Ricardo Sanchez|072691004495711499|ND||||||Prueba||||||5273144||T||3|0|||
```

So when this field (maybe any field?) is `0` it should not be included in the string-to-sign, it should be left blank.

## Steps to Reproduce

This python script shows the error:

```python
import os
import stpmex
import time

client = stpmex.Client(
    empresa='COMPANY',
    priv_key=os.environ['STP_PRIVATE_KEY'],
    priv_key_passphrase=os.environ['STP_PRIVATE_KEY_PASSPHRASE'],
    demo=True,
)

response = client.ordenes.registra(
    conceptoPago='Prueba',
    institucionContraparte="40072",
    monto=1.2,
    nombreBeneficiario="Ricardo Sanchez",
    tipoCuentaBeneficiario=40,
    cuentaBeneficiario="072691004495711499",
    cuentaOrdenante="646180110400000007",
    claveRastreo=f'CR{int(time.time())}',
)
```

And the response is:

```
InsecureRequestWarning: Unverified HTTPS request is being made to host 'demo.stpmex.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
  File "/home/froysm/Projects/Fondeadora/stpmex-python/stpmex/resources/ordenes.py", line 83, in registra
    resp = orden._client.put(endpoint, orden.to_dict())
  File "/home/froysm/Projects/Fondeadora/stpmex-python/stpmex/client.py", line 82, in put
    return self.request('put', endpoint, data)
  File "/home/froysm/Projects/Fondeadora/stpmex-python/stpmex/client.py", line 99, in request
    self._check_response(response)
  File "/home/froysm/Projects/Fondeadora/stpmex-python/stpmex/client.py", line 112, in _check_response
    _raise_description_error_exc(resp)
  File "/home/froysm/Projects/Fondeadora/stpmex-python/stpmex/client.py", line 130, in _raise_description_error_exc
    raise SignatureValidationError(**resp['resultado'])
stpmex.exc.SignatureValidationError: SignatureValidationError(descripcionError='Error validando la firma', id=0)
```

## Context (Environment)

This issue can be observed both in the sandbox (demo.stpmex.com) and in the production environment.

Tested with Python 3.7.9

**Comment by matin** [comment]
@froysm we were able to reproduce the issue in stage, but the current version of the library seems to be working for us in prod. @felipaoo just opened a ticket with STP to figure out what the issue is.

Regardless, I agree that the library should work for both without any issues.

**Comment by matin** [comment]
@froysm one more thing ... thanks for reporting this! Even if it hasn't been causing an issue for us in prod right, it could start at any moment.

**Comment by matin** [comment]
response from STP
![image](https://user-images.githubusercontent.com/98985/102930332-d6ba9280-4461-11eb-872c-ac35fc5134dd.png)

@felipaoo @froysm what about this solution?
```
diff --git a/stpmex/resources/base.py b/stpmex/resources/base.py
index fc0a386..25e263c 100644
--- a/stpmex/resources/base.py
+++ b/stpmex/resources/base.py
@@ -38,6 +38,6 @@ class Resource:
         for k, v in asdict(self).items():
             if isinstance(v, dt.date):
                 base[k] = strftime(v)
-            elif v:
+            elif v is not None:
                 base[k] = v
         return {**base, **dict(firma=self.firma, empresa=self.empresa)}
```

That fixes the problem reported in this issue and ensures `0` is correctly sent in the request body.

**Comment by froysm** [comment]
> response from STP
> ![image](https://user-images.githubusercontent.com/98985/102930332-d6ba9280-4461-11eb-872c-ac35fc5134dd.png)
> 
> @felipaoo @froysm what about this solution?
> 
> ```
> diff --git a/stpmex/resources/base.py b/stpmex/resources/base.py
> index fc0a386..25e263c 100644
> --- a/stpmex/resources/base.py
> +++ b/stpmex/resources/base.py
> @@ -38,6 +38,6 @@ class Resource:
>          for k, v in asdict(self).items():
>              if isinstance(v, dt.date):
>                  base[k] = strftime(v)
> -            elif v:
> +            elif v is not None:
>                  base[k] = v
>          return {**base, **dict(firma=self.firma, empresa=self.empresa)}
> ```
> 
> That fixes the problem reported in this issue and ensures `0` is correctly sent in the request body.

I think I prefer this solution over mine. 👍
