### ISSUE TITLE
block transfers to Asp Integra Opc

### ISSUE THREAD

**Issue by matin** [cuenca-mx/stpmex-python#154]
STP is limiting transfers to Asp Integra Opc to Mx$100. We should validate the transfer on our end vs having STP reject the transaction and hold the money.

There are two solutions:
1. limit to Mx$100
2. block the institution entirely

I recommend solution 2 because of how low Mx$100 is. If the limit was Mx$1,000, for example, I'd suggest setting the validation based on the amount + institution, but it's not worth it for such a low amount.

This change shouldn't be in `clabe-python` since this is a STP restriction and not a Banxico restriction.

**Comment by felipaoo** [comment]
I agree with solution 2. Although STP says that transfers >= $100.0 are not allowed we have seen that they are rejecting transfers < $100.0.

>This change shouldn't be in clabe-python since this is a STP restriction and not a Banxico restriction.

What about to make it in `speid` and return the transfer immediately?

**Comment by matin** [comment]
@felipaoo why in `speid` and not in the client library? Treat it like any other rejection.
