### ISSUE TITLE
CONCEPTO "🥰" is failing

### ISSUE THREAD

**Issue by cuencandres** [cuenca-mx/stpmex-python#161]
El campo concepto de las transacciones debe ser diferente a 🥰, porque está fallando.

**Comment by cuencandres** [comment]
Hoy se dio un caso con el concepto 😘, Debe ser problemas con los emojis

**Comment by froysm** [comment]
> Hoy se dio un caso con el concepto 😘, Debe ser problemas con los emojis

Creo que sí, en realidad en STP hemos tenido muchos problemas con caracteres unicode que en algún punto decidimos usar esta librería para limpiar todos los inputs: https://pypi.org/project/Unidecode/

```python
>>> from unidecode import unidecode
>>> unidecode('Concepto con emoji 🥰')
'Concepto con emoji '
```

**Comment by felipaoo** [comment]
resuelto en https://github.com/cuenca-mx/stpmex-python/pull/196
