### ISSUE TITLE
Increase test coverage to over 99%

### ISSUE THREAD

**Issue by matin** [cuenca-mx/stpmex-python#26]

**Comment by matin** [comment]
@kerycdiaz test coverage is only 93.4% (https://coveralls.io/builds/21500223). You're still missing some tests.

**Comment by matin** [comment]
@ricardo8990 @kerycdiaz status?

**Comment by kerycdiaz** [comment]
@matin Ya solo falta correguir un detalle para que el PR sea aprobado, voy a eso.
